/* Auto-generated by genmsg_cpp for file /home/jfasola/fuerte_workspace/sandbox/p2os/p2os_driver/msg/MotorState.msg */
#ifndef P2OS_DRIVER_MESSAGE_MOTORSTATE_H
#define P2OS_DRIVER_MESSAGE_MOTORSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace p2os_driver
{
template <class ContainerAllocator>
struct MotorState_ {
  typedef MotorState_<ContainerAllocator> Type;

  MotorState_()
  : state(0)
  {
  }

  MotorState_(const ContainerAllocator& _alloc)
  : state(0)
  {
  }

  typedef int32_t _state_type;
  int32_t state;


  typedef boost::shared_ptr< ::p2os_driver::MotorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p2os_driver::MotorState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MotorState
typedef  ::p2os_driver::MotorState_<std::allocator<void> > MotorState;

typedef boost::shared_ptr< ::p2os_driver::MotorState> MotorStatePtr;
typedef boost::shared_ptr< ::p2os_driver::MotorState const> MotorStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::p2os_driver::MotorState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::p2os_driver::MotorState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace p2os_driver

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::p2os_driver::MotorState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::p2os_driver::MotorState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::p2os_driver::MotorState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7a2f37ef2ba405f0c7a15cc72663d6f0";
  }

  static const char* value(const  ::p2os_driver::MotorState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7a2f37ef2ba405f0ULL;
  static const uint64_t static_value2 = 0xc7a15cc72663d6f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::p2os_driver::MotorState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "p2os_driver/MotorState";
  }

  static const char* value(const  ::p2os_driver::MotorState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::p2os_driver::MotorState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32   state\n\
\n\
";
  }

  static const char* value(const  ::p2os_driver::MotorState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::p2os_driver::MotorState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::p2os_driver::MotorState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MotorState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p2os_driver::MotorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::p2os_driver::MotorState_<ContainerAllocator> & v) 
  {
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // P2OS_DRIVER_MESSAGE_MOTORSTATE_H

