/* Auto-generated by genmsg_cpp for file /home/jfasola/fuerte_workspace/sandbox/p2os/p2os_driver/msg/SonarArray.msg */
#ifndef P2OS_DRIVER_MESSAGE_SONARARRAY_H
#define P2OS_DRIVER_MESSAGE_SONARARRAY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace p2os_driver
{
template <class ContainerAllocator>
struct SonarArray_ {
  typedef SonarArray_<ContainerAllocator> Type;

  SonarArray_()
  : header()
  , ranges_count(0)
  , ranges()
  {
  }

  SonarArray_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , ranges_count(0)
  , ranges(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _ranges_count_type;
  int32_t ranges_count;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _ranges_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  ranges;


  typedef boost::shared_ptr< ::p2os_driver::SonarArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p2os_driver::SonarArray_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SonarArray
typedef  ::p2os_driver::SonarArray_<std::allocator<void> > SonarArray;

typedef boost::shared_ptr< ::p2os_driver::SonarArray> SonarArrayPtr;
typedef boost::shared_ptr< ::p2os_driver::SonarArray const> SonarArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::p2os_driver::SonarArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::p2os_driver::SonarArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace p2os_driver

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::p2os_driver::SonarArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::p2os_driver::SonarArray_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::p2os_driver::SonarArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2984921c09aef26ad253c7629937a5bb";
  }

  static const char* value(const  ::p2os_driver::SonarArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2984921c09aef26aULL;
  static const uint64_t static_value2 = 0xd253c7629937a5bbULL;
};

template<class ContainerAllocator>
struct DataType< ::p2os_driver::SonarArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "p2os_driver/SonarArray";
  }

  static const char* value(const  ::p2os_driver::SonarArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::p2os_driver::SonarArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 ranges_count\n\
float64[] ranges\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::p2os_driver::SonarArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::p2os_driver::SonarArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::p2os_driver::SonarArray_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::p2os_driver::SonarArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.ranges_count);
    stream.next(m.ranges);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SonarArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p2os_driver::SonarArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::p2os_driver::SonarArray_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ranges_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ranges_count);
    s << indent << "ranges[]" << std::endl;
    for (size_t i = 0; i < v.ranges.size(); ++i)
    {
      s << indent << "  ranges[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ranges[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // P2OS_DRIVER_MESSAGE_SONARARRAY_H

